# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1442e2ec2cc7e8f945c412b8a07f5e4c"
name = "notify-shop-test"
handle = "notify-shop-test"
application_url = "https://gather-high-constitutional-donate.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "notify-store-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://gather-high-constitutional-donate.trycloudflare.com/auth/callback",
  "https://gather-high-constitutional-donate.trycloudflare.com/auth/shopify/callback",
  "https://gather-high-constitutional-donate.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
